[package]
name = "ca_module_example"
version = "0.1.0"
edition = "2021"

[dependencies]
code_analyzer_parser_interface = {path = "../../core/parser_interface"}

[lib]
crate-type = ["lib", "cdylib", "staticlib"]
